language: ruby
cache: bundler

rvm:
  - 2.3
script: bundle exec rake

language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-24
script:
  - emulator -list-avds
  - emulator -avd Nexus_5_API_23_mars -no-skin &
  - android-wait-for-emulator
after_success:
  - bash echo "Yata!"
