language: ruby
cache: bundler

rvm:
  - 2.3


script: 
  - bundle install
  - bundle exec rake
  - bundle exec rake appium_server
  - bundle exec rake android

language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=x86_64
    - ANDROID_TAG=google_apis
    

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-24
  
before_script:
  - echo no | android create avd --force -n test --target android-24 --path "system-images;android-24;google_apis;x86_64"  --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
  - bash echo "Yata!"
